<a href="https://colab.research.google.com/github/lisabroadhead/udemy-tensorflow/blob/main/00_tensorflow_fundametals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# We're going to cover the most fundamental concepts of tensors using tensorflow

Video: 2.15

we're going to cover
1. intro tensors
2. information from tensos
3. manuipualteinf tensors
4. tensonrs numPy
5. usgin ftf functions (speed up pythong code)
6. excerseis for me!

# Intor to tensros

In [ ]:
# import tensorflow
import tensorflow as tf
print(tf.__version__)

2.8.0


In [ ]:
# Create tensors with tf.constat()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the number direction of a tensor 
scalar.ndim

0

In [ ]:
# create a vector

vector = tf.constant([10,10,10,13])
vector

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([10, 10, 10, 13], dtype=int32)>

In [ ]:
# check diemeions of vector

vector.ndim

1

In [ ]:
# create a matrix

matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
 matrix.ndim

2

In [ ]:
# create another matrix
another_matrix = tf.constant([[11.,13.,.1],[10.,7.,.3],[3.,21.,.2]],dtype = tf.float16)
another_matrix

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[11. , 13. ,  0.1],
       [10. ,  7. ,  0.3],
       [ 3. , 21. ,  0.2]], dtype=float16)>

In [ ]:
# What do you think the number of diemeions of another_matrix?
another_matrix.ndim

2

In [ ]:
tensor = tf.constant([
                      [[1,2,3],
                        [4,5,6]],
                       [[7,8,9],
                        [10,11,12]],
                       [[13,14,15],
                        [16,17,18]]
                      ])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

# Definitions

**Scalar**: single number

**Vector**: number with direction: windspeen & direction

**Matrix**: 2 deminsionsla array of numbers

**Tensor**: an n-dimensional array of numbers (where n can be any number from 0-dimensional = scalar, 1-dimensional = vector)

In [ ]:
tf.Variable

tensorflow.python.ops.variables.Variable

# How to create the same 


In [ ]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# Lets try to change somethingin in the changeable 
changeable_tensor[0] = 7

TypeError: ignored

In [ ]:
# Lets try .assign
changeable_tensor[0].assign(7)

In [ ]:
# Lets try to do the same with unchangeable_tensor
unchangeable_tensor[0]
# unchangeable_tensor[0] = 7
unchangeable_tensor[0].assign(7)

🔑 **Note**:  *Rarely will you need to deicde to use constand or variabels in your tensors*

1. variables can be changed
2. constants cannot be changed

#Random Tensors

Tensors with someabritraty size which containrandom number

In [ ]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
# random_1

random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(9,2))
# random_2


# are they equal
random_1,random_2, random_1 == random_2

In [ ]:
### Shuffly the roder of the elements in a tensor

# shuffle you a tensor (valuable for when you want to shuffle your data so the inherient order doesn't affect learning)
not_shuffled = tf.constant([[10,11],
                            [11,17],
                            [21,31]])
not_shuffled.ndim

2

In [ ]:
not_shuffled

In [ ]:
tf.random.shuffle(not_shuffled)

In [ ]:
tf.random.shuffle(not_shuffled)

In [ ]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10, 11],
       [11, 17],
       [21, 31]], dtype=int32)>

In [ ]:
# 🛠️ read random seed and practicing wring 5 random tensors and shuffling them

In [ ]:
# EXCERSISES
creation_1 = tf.constant([[11,22],
                          [33,44],
                          [55,66],
                         [77,88]])
creation_1
# tf.random.set_seed(1)
tf.random.shuffle(creation_1)

                                                 


<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[33, 44],
       [55, 66],
       [11, 22],
       [77, 88]], dtype=int32)>

In [ ]:
creation_2 = tf.constant([[2,3],
                          [88,9],
                          [300,2],
                          [350,653]])
# tf.random.set_seed(300)
tf.random.shuffle(creation_2,seed=300)


<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 88,   9],
       [350, 653],
       [300,   2],
       [  2,   3]], dtype=int32)>

In [ ]:
creation_3 = tf.Variable([[7,10],
                          [11,13],
                          [21,35]])
tf.random.set_seed(200)
tf.random.shuffle(creation_3,seed=3)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[21, 35],
       [ 7, 10],
       [11, 13]], dtype=int32)>

In [ ]:
creation_4 = tf.Variable([[44,4],[5,55],[66,6],[7,77]])
tf.random.shuffle(creation_4)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[66,  6],
       [44,  4],
       [ 7, 77],
       [ 5, 55]], dtype=int32)>

In [ ]:
creation_5 = tf.constant([[11,7],
                          [13,21],
                          [18,23],
                          [55,100]])
tf.random.shuffle(creation_5)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 55, 100],
       [ 11,   7],
       [ 13,  21],
       [ 18,  23]], dtype=int32)>

In [ ]:
# Other Ways to make tensors
# numpuy.ones

tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# create a tensors of all zeros
tf.zeros(shape=(10,7))

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

# you can also turn numpy into tensors

the main difference between numPy arrays and tensors is that tensors can be run on a GPU. Much faster for numb=erical computing


X = tf.constant = (some_matrix) # cpital matrix for Matrix of tensor

y = tf.constant(vector) # nonCaptial for vector

In [ ]:
import numpy as np

numpy_A = np.arange(1,25, dtype=np.int32)
numpy_A



array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A)
A,A.ndim

(<tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>, 1)

In [ ]:
A = tf.constant(numpy_A,shape=(6,4))
B = tf.constant(numpy_A)
A,B

(<tf.Tensor: shape=(6, 4), dtype=int32, numpy=
 array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

### Getting informtation from tensors

when dealing with tenors you probably want to be aware of the following arrtibutes
- shape
- Rank
- Axis or dimension
- size

In [ ]:
# Create a rank 4 tensor

rank_four = tf.constant([
  [
    [13,14,15],
    [16,17,18],
    [19,20,21]
  ],[
     [34,35,36],
     [27,28,29],
     [38,27,26]
  ],[
   [32,99,76],
   [66,55,77],
   [99,54,32]
  ],[
     [34,35,36],
     [23,34,54],
     [44,33,22]
  ]
])
rank_four

<tf.Tensor: shape=(4, 3, 3), dtype=int32, numpy=
array([[[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21]],

       [[34, 35, 36],
        [27, 28, 29],
        [38, 27, 26]],

       [[32, 99, 76],
        [66, 55, 77],
        [99, 54, 32]],

       [[34, 35, 36],
        [23, 34, 54],
        [44, 33, 22]]], dtype=int32)>

In [ ]:
rank_4 = tf.zeros(shape=[2,3,4,5])
rank_4

In [ ]:
rank_4[0]

In [ ]:
rank_4.shape, rank_4.ndim,tf.size(rank_4)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
2 * 3 *4 *5

In [ ]:
# Pretty Print Statements: Getting sth evarious attributes out of a tensor
print("Datatype of every elementL", rank_4.dtype)
print("Number of dimensins (rank):", rank_4.ndim)
print("Shape of tensor: ", rank_4.shape)
print("Elements along zero access: ", rank_4.shape[0])
print("elements along the last access: ", rank_4.shape[-1])
print("Total number of elements in our tensor:", tf.size(rank_4))
print("Total number of elements in our tensor:", tf.size(rank_4).numpy())

In [ ]:
### Indexing Tensors

# can be indexed like a python list

# get the first 2 elements of each dimension

# my try at what he did
# for x in range(0,tf.size(rank_4).numpy()):
#   print(rank_4[0])
#   print(rank_4[1])

In [ ]:
# Get the first 2 elements in each dimension

somelist = [2,3,4,5]
somelist[:2]

# so here we'd do

rank_4[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
#Get the first element from each dimensions from each index except for th efinal one

# try with rank 4
rank_4[:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4[:1,:1,:,:1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [ ]:
rank_4[:1,:,:1,:1]

<tf.Tensor: shape=(1, 3, 1, 1), dtype=float32, numpy=
array([[[[0.]],

        [[0.]],

        [[0.]]]], dtype=float32)>

In [ ]:
rank_4[:,:1,:1,:1]

<tf.Tensor: shape=(2, 1, 1, 1), dtype=float32, numpy=
array([[[[0.]]],


       [[[0.]]]], dtype=float32)>

In [ ]:
#somelist
somelist[:1]

[2]

In [ ]:
# Create a rank two tensor

rank_2 = tf.zeros(shape=[2,2])
# rank_4 = tf.zeros(shape=[2,3,4,5])
rank_2

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [ ]:
rank_two = tf.constant([[10,7],
                         [11,13]])
rank_two

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [11, 13]], dtype=int32)>

In [ ]:
# get last item
rank_two[:,:-1]

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[10],
       [11]], dtype=int32)>

In [ ]:
somelist[:-1]

[2, 3, 4]

In [ ]:
# Add in extra dimetions to our rank_two tensor = rank_3 tensor
rank_3 = rank_two[...,tf.newaxis]
rank_3

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[11],
        [13]]], dtype=int32)>

In [ ]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2,axis=1) # -1 means expand the final axis

<tf.Tensor: shape=(2, 1, 2), dtype=float32, numpy=
array([[[0., 0.]],

       [[0., 0.]]], dtype=float32)>

In [ ]:
rank_two

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [11, 13]], dtype=int32)>

In [ ]:
rank_two

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [11, 13]], dtype=int32)>

In [ ]:
# practice

rank_1 = tf.constant([[1,2,3,1,3,4,5,3,6,7],
                      [1,2,3,4,5,6,7,89,9,10]])


# need to create a new var in order to see the difference
rank_11 = tf.expand_dims(rank_1,axis=1)
rank_10 = rank_1[...,tf.newaxis]
rank_1, rank_11

(<tf.Tensor: shape=(2, 10), dtype=int32, numpy=
 array([[ 1,  2,  3,  1,  3,  4,  5,  3,  6,  7],
        [ 1,  2,  3,  4,  5,  6,  7, 89,  9, 10]], dtype=int32)>,
 <tf.Tensor: shape=(2, 1, 10), dtype=int32, numpy=
 array([[[ 1,  2,  3,  1,  3,  4,  5,  3,  6,  7]],
 
        [[ 1,  2,  3,  4,  5,  6,  7, 89,  9, 10]]], dtype=int32)>)

In [ ]:
print(rank_11.shape)
print(rank_11.ndim)
print(rank_11.dtype)
print(tf.size(rank_11).numpy())

(2, 1, 10)
3
<dtype: 'int32'>
20


In [ ]:
print("Datatype of every elementL", rank_4.dtype)
print("Number of dimensins (rank):", rank_4.ndim)
print("Shape of tensor: ", rank_4.shape)
print("Elements along zero access: ", rank_4.shape[0])
print("elements along the last access: ", rank_4.shape[-1])
print("Total number of elements in our tensor:", tf.size(rank_4))
print("Total number of elements in our tensor:", tf.size(rank_4).numpy())

Datatype of every elementL <dtype: 'float32'>
Number of dimensins (rank): 4
Shape of tensor:  (2, 3, 4, 5)
Elements along zero access:  2
elements along the last access:  5
Total number of elements in our tensor: tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor: 120


### Manipulating tensors (tensor operations)

you can add values to a tensor suing the addtion operator

+, -, *, /

In [ ]:
tensor = tf.constant([[10,7],
                      [3,4]])
tensor_double = tensor + 20
tensor,tensor_double

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[30, 27],
        [23, 24]], dtype=int32)>)

In [ ]:
# multiplacation

tensor * 10

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 10,  20,  30],
        [ 40,  50,  60]],

       [[ 70,  80,  90],
        [100, 110, 120]],

       [[130, 140, 150],
        [160, 170, 180]]], dtype=int32)>

In [ ]:
# subtraction

tensor - 10

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[-9, -8, -7],
        [-6, -5, -4]],

       [[-3, -2, -1],
        [ 0,  1,  2]],

       [[ 3,  4,  5],
        [ 6,  7,  8]]], dtype=int32)>

In [ ]:
# We can use the tensor flow built in function to
# this is much faster than its counterpart tensor * 10
tf.multiply(tensor,10)

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 10,  20,  30],
        [ 40,  50,  60]],

       [[ 70,  80,  90],
        [100, 110, 120]],

       [[130, 140, 150],
        [160, 170, 180]]], dtype=int32)>

In [ ]:
# tf.add(tensor,10)
# tf.subtract(tensor,100)
tf.divide(tensor,1000)

<tf.Tensor: shape=(3, 2, 3), dtype=float64, numpy=
array([[[0.001, 0.002, 0.003],
        [0.004, 0.005, 0.006]],

       [[0.007, 0.008, 0.009],
        [0.01 , 0.011, 0.012]],

       [[0.013, 0.014, 0.015],
        [0.016, 0.017, 0.018]]])>

### Matrix Multiplcation

In mahcine learning, matrix multiplcaton is one of the most comon tensor operations

There are two rules
1. inner dimensions must match the row2
2. the result matrix has the shape of the inner dimension


In [ ]:
print(tensor)
tf.matmul(tensor,tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
# matrix multipliication with pythong operator @

In [ ]:
# Creat a tensor of (3,2)

X = tf.constant([[1,2,1],
                [0,1,0],
                [2,3,4]])
Y = tf.constant([[2,5],
                 [6,7],
                 [1,8]])
tf.matmul(X,Y)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[15, 27],
       [ 6,  7],
       [26, 63]], dtype=int32)>

In [ ]:
X @ Y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[15, 27],
       [ 6,  7],
       [26, 63]], dtype=int32)>

In [ ]:
## https://www.mathsisfun.com/algebra/matrix-introduction.html
## https://www.mathsisfun.com/algebra/matrix-multiplying.html

In [ ]:
# Challendge

Q = tf.constant([[1,2,],
             [3,4],
             [5,6]])

U = tf.constant([[12,13],
                 [13,14],
                 [15,16]])

Q, U

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[12, 13],
        [13, 14],
        [15, 16]], dtype=int32)>)

In [ ]:
# Q @ tf.reshape(U,shape=(2,3))

In [ ]:
# tf.matmul(Q, tf.reshape(U, shape=(2,3)))
tf.reshape(Q, shape=(2,3)), U

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[12, 13],
        [13, 14],
        [15, 16]], dtype=int32)>)

### The dot product

Matrix muliplication is also referred to as the dot product

you can perform matrix muliplication using:

* t.matmul()
* tf.tensordot()

In [ ]:
X = tf.constant([
                 [1,2],
                 [3,4],
                 [5,6]
])
Y = tf.constant([
                 [10,11],
                 [12,13],
                 [14,15]
])
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10, 11],
        [12, 13],
        [14, 15]], dtype=int32)>)

In [ ]:
# perform the dot product on X and Y requires X and Y to be transposed

tf.tensordot(tf.transpose(X),Y,axes=1)
# tf.matmul(X,Y)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 4, 21],
       [13, 41],
       [ 6, 37]], dtype=int32)>

In [ ]:
# Perform matrix muliplication between X and Y (reansposed)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 32,  38,  44],
       [ 74,  88, 102],
       [116, 138, 160]], dtype=int32)>

In [ ]:
# Perform matrix muliplication between X and Y
tf.matmul(X,tf.reshape(Y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 36,  39,  42],
       [ 82,  89,  96],
       [128, 139, 150]], dtype=int32)>

In [ ]:
# check the values of Y, reshape Y, and transpose Y
print("Normal Y:")
print(Y, "/n" )
print("Y reshaped to (2,3)")
print(tf.reshape(Y, shape=(2,3)), "/n")
print("Y transposed:")
print(tf.transpose(Y))

Normal Y:
tf.Tensor(
[[2 5]
 [6 7]
 [1 8]], shape=(3, 2), dtype=int32) /n
Y reshaped to (2,3)
tf.Tensor(
[[2 5 6]
 [7 1 8]], shape=(2, 3), dtype=int32) /n
Y transposed:
tf.Tensor(
[[2 6 1]
 [5 7 8]], shape=(2, 3), dtype=int32)


###  Changing the datatype



In [ ]:
# Create a new tensor with a default daattype (float32)

B = tf.constant([1.7,7.4])
B.dtype

tf.float32

In [ ]:
C = tf.constant([7,10])
C.dtype

tf.int32

In [ ]:
# change from flota32 to float16 (reduced percision)

D = tf.cast(B,dtype=tf.float16)
D.dtype

tf.float16

In [ ]:
# Change from int32 to float32

E = tf.cast(C, dtype=tf.float32)
E,E.dtype


(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>,
 tf.float32)

### Aggeration Tensors

condeseing them from multiple vlaues down to smaller values

In [ ]:
# Getting the absolute vlaues

D = tf.constant([-7,-10],
                [4,10])
D

TypeError: ignored

In [ ]:
# get abs vlaues - turn negatives to positives

tf.abs(D)

<tf.Tensor: shape=(24,), dtype=float16, numpy=
array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.],
      dtype=float16)>

# Lets got through the following forms of aggerigation
* get min
* get max
* get mean
* get sum

In [ ]:
tf.reduce_mean(D)

<tf.Tensor: shape=(), dtype=float16, numpy=12.5>

In [ ]:
tf.reduce_sum(D)

<tf.Tensor: shape=(), dtype=float16, numpy=300.0>

In [ ]:
tf.reduce_max(D)

<tf.Tensor: shape=(), dtype=float16, numpy=24.0>

In [ ]:
tf.reduce_min(D)

<tf.Tensor: shape=(), dtype=float16, numpy=1.0>

In [ ]:
tf.size(D),  D.shape, D.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=24>, TensorShape([24]), 1)

# Excerise - find the varients and standar deviation of our D tensor

* varient - tensor of any fata type

In [ ]:
# varient
tf.data.experimental.from_variant(10,D)

<_VariantDataset element_spec=[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24.]>

In [ ]:
# Standard deviation - how disperated the data is compared to the mean

#to get variance we need access to tensorflow probaility

import tensorflow_probability as tfp

G = tfp.stats.variance(D)
G

<tf.Tensor: shape=(), dtype=float16, numpy=47.9>

In [ ]:
# Standard Deviation

# needs to be a float

tf.math.reduce_std(tf.cast(D, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=6.922187>

### TypeError - go to gocumentation and see what kinds of types they're using in the workflow

# Find postional, maximumu and minimum of a tensor
- postional
- maximumu
- minimum

In [ ]:
H = tf.constant([
                 [4.,5.,6.],
                 [5.,6.,7.],
                 [8.,9.,10.],
                 [21.,23.,34.],
                 [45.,46.,47.],
                 [78.,567.,90.]
])
tf.reduce_max(H), tf.reduce_min(H), tf.math.reduce_variance(H)

(<tf.Tensor: shape=(), dtype=float32, numpy=567.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=4.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=15988.694>)

In [ ]:
### Find the 
H, tf.math.argmax(H),tf.math.argmin(H)

(<tf.Tensor: shape=(6, 3), dtype=float32, numpy=
 array([[  4.,   5.,   6.],
        [  5.,   6.,   7.],
        [  8.,   9.,  10.],
        [ 21.,  23.,  34.],
        [ 45.,  46.,  47.],
        [ 78., 567.,  90.]], dtype=float32)>,
 <tf.Tensor: shape=(3,), dtype=int64, numpy=array([5, 5, 5])>,
 <tf.Tensor: shape=(3,), dtype=int64, numpy=array([0, 0, 0])>)

In [ ]:
# Create a new tensor for finding posMax and posMin
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
# find the postional maxmini - agmax
tf.argmax(F), tf.argmax(F).numpy()

(<tf.Tensor: shape=(), dtype=int64, numpy=42>, 42)

In [ ]:
# index on our largest value position
F[tf.argmax(F)], F[tf.argmax(F)].numpy() 

(<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>, 0.9671384)

In [ ]:
# find the max value F

tf.reduce_max(F), tf.reduce_max(F).numpy()

(<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>, 0.9671384)

In [ ]:
# check for equality
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
# Find the posMin
tf.argmin(F), tf.argmin(F).numpy()

(<tf.Tensor: shape=(), dtype=int64, numpy=16>, 16)

In [ ]:
# find min of posMin index
F[tf.argmin(F)], F[tf.argmin(F)].numpy()

(<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>, 0.009463668)

### Practice

In [ ]:
T = tf.random.Generator.from_seed(50)
T.normal(shape=(2, 3, 3, 10))


### Squeezing a tensor (removing all the single dimensions)

In [ ]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,50))
G

In [ ]:
G.shape

TensorShape([])

In [ ]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape


### ont-hot encoding tensors
- create a list of indicies

In [ ]:
some_list = [0,1,2,3]

# one hot encode
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
# speicifty custom values one hot encoding

tf.one_hot(some_list, depth=4,on_value=2 ,off_value=0)

### squareing, log, squareroot


In [ ]:
# c
H = tf.range(1,10)
H


<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
# square
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
# square root

tf.sqrt(tf.cast(tf.square(H), dtype=tf.float32))



<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.9999999 , 2.9999998 , 3.9999998 , 5.        ,
       5.9999995 , 6.9999995 , 7.9999995 , 9.        ], dtype=float32)>

In [ ]:
# log
# tf.math.log(H)

tf.cast(H,dtype=tf.float32)

<tf.Tensor: shape=(9,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)>

### Excersice

In [ ]:
# 1. 

H1 = tf.range(101)


# tf.floor(H1).numpy()

tf.floor(tf.cast(H1,dtype=tf.float32)).numpy()



array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
        11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,
        22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,
        33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,
        44.,  45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,
        55.,  56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,
        66.,  67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,
        77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,
        88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,
        99., 100.], dtype=float32)

In [ ]:
x = tf.constant([1.3324, -1.5, 5.555, -2.532, 0.99, float("inf")])
# x

tf.floor(x).numpy()

array([ 1., -2.,  5., -3.,  0., inf], dtype=float32)

In [ ]:
# 2. expo
H2 = tf.range(5)
tf.math.exp(tf.cast(H2,dtype=tf.float32))

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([ 1.       ,  2.7182817,  7.389056 , 20.085537 , 54.59815  ],
      dtype=float32)>

In [ ]:
# 3. equal
y = tf.constant([2,3,4])
x = tf.constant([2,0,4])
tf.equal(y,x)

<tf.Tensor: shape=(3,), dtype=bool, numpy=array([ True, False,  True])>

In [ ]:
### Tensors and numpy

J = tf.constant(np.array([3.,7.,8.]))
J1 = tf.constant([3.,7.,8.])
J, J1

(<tf.Tensor: shape=(3,), dtype=float64, numpy=array([3., 7., 8.])>,
 <tf.Tensor: shape=(3,), dtype=float32, numpy=array([3., 7., 8.], dtype=float32)>)

In [ ]:
# np.array(J)
np.array(J1),type(np.array(J1)),type(np.array(J))

(array([3., 7., 8.], dtype=float32), numpy.ndarray, numpy.ndarray)

In [ ]:
# J.numpy(), type(J.numpy())
# J = tf.constant([3.])
# J.numpy()[0]

3.0

# default types of each slightly different

### 🔑 creating a tensor in numpy vrs. tensor will create a different data type. Also tensors can be run on a GPU and TPU for faster computing

In [ ]:
numpy_J = tf.constant(np.array([3.,7.,10.]))
tensor_J = tf.constant([3.,7.,10.])
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

# Finding acces to GPU
fastest
1. TPU
2. GPU
3. CPU

🔑 Note: If you hve acces to a CUDA enabled GPU, tensorflow will automatically use it whenever possible

In [ ]:
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Mon May 16 16:26:15 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   55C    P8    10W /  70W |      3MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------